In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [15]:
df = pd.read_csv('dummy/Dataset.csv')

In [16]:
df.head()

,class,x1,y1,z1,x2,y2,z2,x3,y3,z3,...,z30,x31,y31,z31,x32,y32,z32,x33,y33,z33
0,Takbir,0,0,0,-0.006072,0.010336,-0.024488,-0.010014,0.009360,-0.024497,...,-0.333901,0.030949,-0.681574,-0.341826,-0.059583,-0.700780,-0.189067,0.052450,-0.705191,-0.199248
1,Takbir,0,0,0,-0.005821,0.009790,-0.026076,-0.009719,0.008841,-0.026094,...,-0.365845,0.030675,-0.682236,-0.357962,-0.059955,-0.701333,-0.203613,0.050976,-0.707035,-0.200519
2,Takbir,0,0,0,-0.005426,0.009380,-0.026898,-0.009217,0.008475,-0.026920,...,-0.365486,0.030195,-0.682071,-0.349673,-0.059872,-0.701855,-0.207292,0.049517,-0.708613,-0.193603
3,Takbir,0,0,0,-0.005126,0.009342,-0.026562,-0.008775,0.008494,-0.026586,...,-0.368412,0.029982,-0.682147,-0.351376,-0.059355,-0.701110,-0.207402,0.048174,-0.708927,-0.193129
4,Takbir,0,0,0,-0.005062,0.009319,-0.027209,-0.008746,0.008471,-0.027236,...,-0.353886,0.030043,-0.682409,-0.341411,-0.059360,-0.701135,-0.194244,0.048187,-0.709517,-0.177988

In [17]:
df.tail()

,class,x1,y1,z1,x2,y2,z2,x3,y3,z3,...,z30,x31,y31,z31,x32,y32,z32,x33,y33,z33
4576,Salam Kiri,0,0,0,0.005785,0.019579,-0.025313,0.005519,0.019977,-0.025199,...,-0.535438,0.158992,-0.400694,-0.506718,0.081061,-0.424589,-0.608819,0.176378,-0.439459,-0.570147
4577,Salam Kiri,0,0,0,0.005825,0.019643,-0.025457,0.005669,0.020084,-0.025351,...,-0.481346,0.158630,-0.420133,-0.464804,0.087788,-0.427585,-0.538342,0.179912,-0.439656,-0.509540
4578,Salam Kiri,0,0,0,0.005849,0.019727,-0.025626,0.005726,0.020189,-0.025522,...,-0.489143,0.158341,-0.425175,-0.460632,0.090313,-0.428580,-0.546524,0.181561,-0.439713,-0.502891
4579,Salam Kiri,0,0,0,0.005834,0.019799,-0.026716,0.005621,0.020274,-0.026626,...,-0.493155,0.157861,-0.426392,-0.473836,0.096729,-0.432732,-0.541853,0.185277,-0.439854,-0.510393
4580,Salam Kiri,0,0,0,0.005884,0.019856,-0.026492,0.005636,0.020331,-0.026401,...,-0.500063,0.157039,-0.428738,-0.480085,0.096056,-0.435067,-0.548832,0.184679,-0.440090,-0.516001

In [18]:
X = df.drop('class', axis = 1) #features
y = df['class'] #target value

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [20]:
from sklearn.pipeline import make_pipeline  #ML pipeline
from sklearn.preprocessing import StandardScaler #ML pipeline
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn import metrics

In [21]:
pipelines = {
    'lr':make_pipeline(StandardScaler(), LogisticRegression()),
    'rc':make_pipeline(StandardScaler(), RidgeClassifier()),
    'rf':make_pipeline(StandardScaler(), RandomForestClassifier()),
    'gb':make_pipeline(StandardScaler(), GradientBoostingClassifier()),
}

In [22]:
fit_models = {}
for algo, pipeline in pipelines.items():
    model = pipeline.fit(X_train.values, y_train)
    fit_models[algo] = model

C:\Users\LENOVO\anaconda3\envs\PA\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

In [23]:
fit_models

{'lr': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('logisticregression', LogisticRegression())]),
 'rc': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('ridgeclassifier', RidgeClassifier())]),
 'rf': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('randomforestclassifier', RandomForestClassifier())]),
 'gb': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('gradientboostingclassifier', GradientBoostingClassifier())])}

In [24]:
from sklearn.metrics import accuracy_score # Accuracy metrics 
import pickle

In [25]:
for algo, model in fit_models.items():
    yhat = model.predict(X_test.values)
    print(algo, accuracy_score(y_test, yhat))

lr 1.0
rc 0.9992727272727273
rf 1.0
gb 0.9992727272727273

In [26]:
fit_models['rf'].predict(X_test.values)

array(['Takhiyat Akhir', 'Sujud', 'Salam Kiri', ..., 'Salam Kiri',
       'Salam Kanan', 'Takbir'], dtype=object)

In [27]:
with open('model/model.sav', 'wb') as f:
    pickle.dump(fit_models['rf'], f)